import { useEffect, useState } from 'react';
import { AppLayout } from '@/components/layout/AppLayout';
import { Button } from '@/components/ui/button';
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card';
import { Input } from '@/components/ui/input';
import { listPipelineTemplates, createPipelineFromTemplate, type PipelineTemplate } from '@/integrations/directus/pipelineTemplates';
import { TemplatePreview } from '@/components/TemplatePreview';
import { useNavigate, useSearchParams } from 'react-router-dom';
import { toast } from '@/hooks/use-toast';
export default function PipelineTemplateWizard(){const [step,setStep]=useState(1);const [templates,setTemplates]=useState<PipelineTemplate[]>([]);const [selected,setSelected]=useState<PipelineTemplate>();const [params]=useSearchParams();const nav=useNavigate();useEffect(()=>{listPipelineTemplates().then(ts=>{setTemplates(ts);const id=params.get('template');if(id)setSelected(ts.find(t=>t.id===id));}).catch(()=>{});},[params]);const confirm=async()=>{if(!selected)return;try{await createPipelineFromTemplate(selected);toast({title:'Pipeline criada com sucesso'});nav('/definicoes/pipelines')}catch{toast({title:'Erro ao criar pipeline',variant:'destructive'})}};return <AppLayout><div className="p-4 max-w-4xl mx-auto space-y-6"><h1 className="text-2xl font-semibold">Nova pipeline</h1><div className="flex gap-3 text-sm">{['Escolher','Pré-visualizar e personalizar','Confirmar'].map((x,i)=><span key={x} className={i+1===step?'font-semibold text-primary':'text-muted-foreground'}>{i+1}. {x}</span>)}</div>{step===1&&<Card><CardHeader><CardTitle>Escolha um template</CardTitle></CardHeader><CardContent className="grid sm:grid-cols-2 gap-3">{templates.map(t=><button key={t.id} className={`text-left rounded-lg border p-3 ${selected?.id===t.id?'ring-2 ring-primary':''}`} onClick={()=>setSelected(t)}><div className="font-medium">{t.name}</div><TemplatePreview stages={t.stages} compact/></button>)}<Button disabled={!selected} onClick={()=>setStep(2)}>Continuar</Button></CardContent></Card>}{step===2&&selected&&<Card><CardHeader><CardTitle>Pré-visualizar e personalizar</CardTitle></CardHeader><CardContent className="space-y-4"><Input value={selected.name} onChange={e=>setSelected({...selected,name:e.target.value})}/><TemplatePreview stages={selected.stages}/><div className="flex gap-2"><Button variant="outline" onClick={()=>setStep(1)}>Voltar</Button><Button onClick={()=>setStep(3)}>Continuar</Button></div></CardContent></Card>}{step===3&&selected&&<Card><CardHeader><CardTitle>Confirmar criação</CardTitle></CardHeader><CardContent className="space-y-4"><p>Será criada a pipeline <strong>{selected.name}</strong> com {selected.stages.length} etapas.</p><TemplatePreview stages={selected.stages}/><Button variant="outline" onClick={()=>setStep(2)}>Voltar</Button> <Button onClick={confirm}>Criar pipeline</Button></CardContent></Card>}</div></AppLayout>}
