import { useRef, useState } from "react";
import { Link, useParams } from "react-router-dom";
import { formatDistanceToNow } from "date-fns";
import { pt } from "date-fns/locale";
import { Copy, FileText, Instagram, Mail, MessageCircle, Phone, Plus, ShoppingCart, Star } from "lucide-react";
import { Avatar, AvatarFallback } from "@/components/ui/avatar";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Card, CardContent } from "@/components/ui/card";
import { Sheet, SheetContent, SheetHeader, SheetTitle, SheetTrigger } from "@/components/ui/sheet";
import { Skeleton } from "@/components/ui/skeleton";
import { Tabs, TabsContent, TabsList, TabsTrigger } from "@/components/ui/tabs";
import { Textarea } from "@/components/ui/textarea";
import { useCustomer360Remodeled, type Customer360Event } from "@/hooks/useCustomer360Remodeled";

const tabs = ["timeline", "propostas", "compras", "comunicacao", "notas"] as const;
const labels: Record<(typeof tabs)[number], string> = { timeline: "Timeline", propostas: "Propostas", compras: "Compras", comunicacao: "Comunicação", notas: "Notas" };
function Icon({ channel }: { channel: string }) { return channel === "whatsapp" ? <MessageCircle className="size-4 text-emerald-600" /> : channel === "email" ? <Mail className="size-4 text-blue-600" /> : channel === "call" ? <Phone className="size-4 text-violet-600" /> : channel === "proposal" ? <FileText className="size-4 text-amber-600" /> : <Star className="size-4 text-slate-500" />; }
function Empty({ children }: { children: string }) { return <div className="py-16 text-center text-sm text-muted-foreground">{children}</div>; }
function EventCard({ item }: { item: Customer360Event }) { return <Card className="shadow-sm"><CardContent className="flex gap-3 p-4"><div className="grid size-9 shrink-0 place-items-center rounded-full bg-muted"><Icon channel={item.channel} /></div><div className="min-w-0"><div className="flex gap-2"><p className="font-medium">{item.title}</p><Badge variant="secondary" className="text-[10px]">{item.channel}</Badge></div>{item.summary && <p className="mt-1 text-sm text-muted-foreground">{item.summary}</p>}<p className="mt-2 text-xs text-muted-foreground">{item.occurredAt ? formatDistanceToNow(new Date(item.occurredAt), { addSuffix: true, locale: pt }) : ""}</p></div></CardContent></Card>; }
function QuickActions({ phone, email }: { phone?: string; email?: string }) { const actions = [{ title: "Ligar", icon: Phone, href: phone ? `tel:${phone}` : "#" }, { title: "WhatsApp", icon: MessageCircle, href: phone ? `https://wa.me/${phone.replace(/\D/g, "")}` : "#" }, { title: "Email", icon: Mail, href: email ? `mailto:${email}` : "#" }, { title: "Proposta", icon: FileText, href: "/propostas/nova" }]; return <Sheet><SheetTrigger asChild><Button variant="secondary" className="md:hidden">Ações</Button></SheetTrigger><SheetContent side="bottom" className="rounded-t-2xl"><SheetHeader><SheetTitle>Ações rápidas</SheetTitle></SheetHeader><div className="mt-5 grid grid-cols-2 gap-3">{actions.map(({ title, icon: ActionIcon, href }) => <a key={title} href={href} className="flex min-h-24 flex-col items-center justify-center gap-2 rounded-xl border shadow-sm"><ActionIcon className="size-6" />{title}</a>)}</div></SheetContent></Sheet>; }
function Loading() { return <div className="min-h-screen bg-muted/30"><div className="h-44 bg-gradient-to-r from-indigo-700 via-violet-700 to-fuchsia-600 p-5"><Skeleton className="size-14 rounded-full" /></div><div className="space-y-3 p-4">{[1, 2, 3].map(i => <Skeleton key={i} className="h-24" />)}</div></div>; }

export default function Customer360() {
  const { id } = useParams(); const [active, setActive] = useState<(typeof tabs)[number]>("timeline"); const [note, setNote] = useState(""); const touch = useRef<number | null>(null); const { data, isLoading, error, createNote } = useCustomer360Remodeled(id);
  if (isLoading) return <Loading />;
  if (error || !data) return <Empty>{error instanceof Error ? error.message : "Não foi possível carregar o contacto."}</Empty>;
  const contact = data.contact || {}; const name = contact.company_name || contact.contact_name || contact.name || "Contacto"; const phone = contact.phone || contact.mobile || contact.whatsapp_number; const email = contact.email;
  const swipe = (end: number) => { if (touch.current === null || Math.abs(end - touch.current) < 50) return; const at = tabs.indexOf(active); setActive(tabs[Math.max(0, Math.min(tabs.length - 1, at + (end < touch.current ? 1 : -1)))]); touch.current = null; };
  const addNote = async () => { if (!note.trim()) return; await createNote(note.trim()); setNote(""); };
  const communications = data.timeline.filter(item => ["whatsapp", "email", "instagram"].includes(item.channel));
  return <main className="min-h-screen bg-muted/30" onTouchStart={e => { touch.current = e.touches[0].clientX; }} onTouchEnd={e => swipe(e.changedTouches[0].clientX)}>
    <header className="sticky top-0 z-30 bg-gradient-to-r from-indigo-700 via-violet-700 to-fuchsia-600 text-white shadow-md"><div className="mx-auto max-w-5xl p-4"><div className="flex gap-3"><Avatar className="size-14 border-2 border-white/40"><AvatarFallback className="bg-white/20 text-white">{name.slice(0, 2).toUpperCase()}</AvatarFallback></Avatar><div className="min-w-0 flex-1"><h1 className="truncate text-lg font-bold">{name}</h1><p className="truncate text-sm text-white/80">{contact.company_name && contact.contact_name ? contact.contact_name : contact.city || "Cliente"}</p><div className="mt-1 flex items-center gap-1 text-sm"><Star className="size-4 fill-yellow-300 text-yellow-300" />{Math.round(Number(contact.score || contact.lead_score || 0))} score</div></div><QuickActions phone={phone} email={email} /><div className="hidden gap-2 md:flex"><a href={phone ? `tel:${phone}` : "#"}><Button size="icon" variant="secondary"><Phone /></Button></a><a href={phone ? `https://wa.me/${phone.replace(/\D/g, "")}` : "#"}><Button size="icon" variant="secondary"><MessageCircle /></Button></a><a href={email ? `mailto:${email}` : "#"}><Button size="icon" variant="secondary"><Mail /></Button></a><Link to="/propostas/nova"><Button size="icon" variant="secondary"><FileText /></Button></Link></div></div><div className="mt-3 grid gap-2 border-t border-white/20 pt-3 text-sm sm:grid-cols-2">{phone && <div className="flex items-center gap-2 truncate"><Phone className="size-4" />{phone}<button onClick={() => navigator.clipboard?.writeText(phone)} aria-label="Copiar telefone"><Copy className="size-3" /></button></div>}{email && <div className="flex items-center gap-2 truncate"><Mail className="size-4" />{email}</div>}</div></div></header>
    <Tabs value={active} onValueChange={value => setActive(value as typeof active)} className="mx-auto max-w-5xl"><div className="sticky top-[156px] z-20 overflow-x-auto border-b bg-background/95 backdrop-blur"><TabsList className="h-auto w-max min-w-full justify-start rounded-none bg-transparent p-0">{tabs.map(tab => <TabsTrigger key={tab} value={tab} className="rounded-none border-b-2 border-transparent px-4 py-3 data-[state=active]:border-primary">{labels[tab]}</TabsTrigger>)}</TabsList></div>
      <TabsContent value="timeline" className="space-y-3 p-4">{data.timeline.length ? data.timeline.map(item => <EventCard key={item.id} item={item} />) : <Empty>Sem atividade registada.</Empty>}</TabsContent>
      <TabsContent value="propostas" className="space-y-3 p-4">{data.quotations.length ? data.quotations.map(q => <Card key={q.id} className="shadow-sm"><CardContent className="flex items-center justify-between p-4"><div><p className="font-medium">{q.quotation_number || `Proposta ${q.id}`}</p><p className="text-sm text-muted-foreground">{q.status} · {Number(q.total_amount || 0).toLocaleString("pt-PT", { style: "currency", currency: "EUR" })}</p></div><Link to={`/propostas/${q.id}`}><Button variant="outline">Abrir</Button></Link></CardContent></Card>) : <Empty>Sem propostas registadas.</Empty>}</TabsContent>
      <TabsContent value="compras" className="space-y-3 p-4">{data.orders.length ? data.orders.map(order => <Card key={order.id} className="shadow-sm"><CardContent className="flex items-center gap-3 p-4"><ShoppingCart className="size-5 text-primary" /><div><p className="font-medium">#{order.order_number || order.wc_order_id || order.id}</p><p className="text-sm text-muted-foreground">{order.status} · {Number(order.total || 0).toLocaleString("pt-PT", { style: "currency", currency: "EUR" })}</p></div></CardContent></Card>) : <Empty>Não existem encomendas para este contacto.</Empty>}</TabsContent>
      <TabsContent value="comunicacao" className="space-y-3 p-4">{communications.length ? communications.map(item => <EventCard key={item.id} item={item} />) : <Empty>WhatsApp, Email e Instagram surgirão aqui.</Empty>}<div className="grid grid-cols-3 gap-2"><Button variant="outline"><MessageCircle />WhatsApp</Button><Button variant="outline"><Mail />Email</Button><Button variant="outline"><Instagram />IG</Button></div></TabsContent>
      <TabsContent value="notas" className="space-y-3 p-4"><Card className="shadow-sm"><CardContent className="p-3"><Textarea value={note} onChange={e => setNote(e.target.value)} placeholder="Adicionar nota…" /><div className="mt-2 flex justify-end"><Button onClick={addNote} disabled={!note.trim()}><Plus />Adicionar</Button></div></CardContent></Card>{data.notes.length ? data.notes.map(item => <Card key={item.id} className="shadow-sm"><CardContent className="p-4"><p>{item.body}</p><p className="mt-2 text-xs text-muted-foreground">{item.date_created && formatDistanceToNow(new Date(item.date_created), { addSuffix: true, locale: pt })}</p></CardContent></Card>) : <Empty>Sem notas. Adicione a primeira.</Empty>}</TabsContent>
    </Tabs></main>;
}
